spring:
  redis:
    port: 6379
    host: 192.168.55.22
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: dev
    url: jdbc:mysql://192.168.55.22/appcenter
    password: test1234
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  sql:
    init:
      mode: always
  servlet:
    multipart:
      maxFileSize: 15MB
      maxRequestSize: 15MB
